name = "hive-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[alias]
"@graphql-tools/wrap" = "../../packages/wrap/src/index.ts"
"@graphql-tools/batch-delegate" = "../../packages/batch-delegate/src/index.ts"
"@graphql-tools/delegate" = "../../packages/delegate/src/index.ts"
"@graphql-hive/signal" = "../../packages/signal/src/index.ts"