name = "hive-gateway"
main = "src/index.ts"
compatibility_date = "2025-05-05"

[alias]
"@graphql-tools/wrap" = "../../packages/wrap/src/index.ts"
"@graphql-tools/batch-delegate" = "../../packages/batch-delegate/src/index.ts"
"@graphql-tools/delegate" = "../../packages/delegate/src/index.ts"
"@graphql-hive/signal" = "../../packages/signal/src/index.ts"
"@graphql-hive/logger" = "../../packages/logger/src/index.ts"
